/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/P0ot4TjIbpI
 */
import { Avatar } from "@/components/ui/avatar";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function Chat() {
  return (
    <div className="h-full flex flex-col bg-gray-100 dark:bg-gray-900 p-4 space-y-4">
      <div className="flex-1 overflow-y-auto space-y-4">
        <div className="flex items-end space-x-2">
          <Avatar
            className="h-10 w-10"
            src="/placeholder.svg?height=40&width=40"
          />
          <div className="p-3 rounded-lg bg-gray-200 dark:bg-gray-800">
            <p className="text-sm text-gray-900 dark:text-gray-100">
              Hello, how can I assist you today?
            </p>
          </div>
        </div>
        <div className="flex items-end justify-end space-x-2">
          <div className="p-3 rounded-lg bg-blue-500 text-white">
            <p className="text-sm">I need help with my account.</p>
          </div>
          <Avatar
            className="h-10 w-10"
            src="/placeholder.svg?height=40&width=40"
          />
        </div>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-700">
        <div className="space-x-2 p-2">
          <Textarea
            className="flex-1 rounded-lg border-gray-300 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-300"
            placeholder="Type your message..."
          />
          <Button>Send</Button>
        </div>
      </div>
    </div>
  );
}
